version: '3'

vars:
  PROD_PORT: 8321
  DEV_PORT: 8323
  PROD_IMAGE: eink-entrance-display-backend:latest
  DEBUG_IMAGE: eink-entrance-display-backend-debug:latest

tasks:
  build_base_docker_container:
    internal: true
    cmds:
      - docker build --tag eink-entrance-display-backend-base:latest deploy/docker-containers/base

  build_docker:
    desc: Build the docker
    cmds:
      - task: build_base_docker_container
      - docker build --tag {{.PROD_IMAGE}} deploy/docker-containers/prod

  run_docker_daemon:
    desc: Run the docker so it restarts on reboot
    cmds:
      - docker run -d --restart unless-stopped --publish {{.PROD_PORT}}:{{.PROD_PORT}} {{.PROD_IMAGE}}

  debug_build_docker:
    desc: Build the docker, while preserving intermediate layers
    cmds:
      - task: build_base_docker_container
      - docker build --tag {{.DEBUG_IMAGE}} --rm=false deploy/docker-containers/debug

  debug_run_docker:
    desc: Run the docker, interactive for debugging (press CTRL-C to exit)
    cmds:
      - docker run -it --restart unless-stopped --publish {{.PROD_PORT}}:{{.PROD_PORT}} --mount type=bind,source="$(pwd)",target=/app {{.DEBUG_IMAGE}}

  debug_run:
    desc: Run the server outside the server, for debugging (inside devcontainer only)
    cmds:
      - /usr/local/bin/uvicorn src.eink_backend.main:app --reload --host 0.0.0.0 --port {{.DEV_PORT}}

  run_tests:
    desc: Build debug docker and run the tests (inside devcontainer only)
    cmds:
      - bash -c "cd /app; pytest"


  default:
    cmds:
      - task --list