version: '3'

tasks:
  debug_run:
    desc: Run the server outside the server, for debugging
    cmds:
      - /home/pi/.local/bin/uvicorn main:app --reload --host 0.0.0.0 --port 8321

  debug_build_docker:
    desc: Build the docker, while preserving intermediate layers
    cmds:
      - docker build --tag eink-entrance-display-backend:latest --rm=false .

  build_docker:
    desc: Build the docker
    cmds:
      - docker build --tag eink-entrance-display-backend:latest .

  debug_run_docker:
    desc: Run the docker, interactive for debugging (press CTRL-C to exit)
    cmds:
      - docker run --rm -it --publish 8321:8321 eink-entrance-display-backend:latest

  run_docker_daemon:
    desc: Run the docker so it restarts on reboot
    cmds:
      - docker run -d --restart unless-stopped --publish 8321:8321 eink-entrance-display-backend:latest
